#!/usr/bin/env python3
"""Invert EmuTOS's own US keyboard table into an ASCII -> scancode map.

The servant receives characters over the serial port and has to hand
EmuTOS scancodes, which is the same journey EmuTOS makes in the other
direction every time a key is pressed. Writing the table out by hand
would be guessing at the answer to a question this source tree already
answers: bios/keyb_us.h is exactly scancode -> character, for the
unshifted and shifted cases, and it is the table EmuTOS will use to
turn our scancodes back into characters. Inverting it is the only way
to be sure the round trip closes.

Output is iofw/uart_keymap.h: one byte per ASCII code, 0 for "no key
produces this", otherwise the scancode with bit 7 set when the shifted
table is the one that matched. Scancodes are 7-bit, so the flag is free.
"""
import re
import sys

SRC = 'emutos/bios/keyb_us.h'
OUT = 'iofw/uart_keymap.h'

# Scancodes above this are the numeric keypad and the function keys. The
# keypad duplicates the digits and would win the inversion for '0'-'9'
# purely by being scanned later; the main row is what a serial keyboard
# means by a digit, so the keypad is left out rather than ordered around.
MAIN_LAST = 0x39


def parse(src, name):
    m = re.search(r'static const UBYTE %s\[\] = \{(.*?)\};' % name, src, re.S)
    if not m:
        raise SystemExit('%s: %s not found' % (SRC, name))
    body = m.group(1)
    # Split on tokens, not on commas: one of the entries is ',' and a
    # comma split cuts it in half.
    tok = re.compile(r"'(\\.|[^'\\])'|(0x[0-9A-Fa-f]+|\d+)")
    unescape = {'\\\\': '\\', "\\'": "'", '\\"': '"'}
    vals = []
    for ch, num in tok.findall(body):
        if num:
            vals.append(int(num, 0))
        else:
            vals.append(ord(unescape.get(ch, ch)))
    return vals


def main():
    src = open(SRC).read()
    norm = parse(src, 'keytbl_us_norm')
    shft = parse(src, 'keytbl_us_shft')
    if len(norm) != 128 or len(shft) != 128:
        raise SystemExit('expected 128 entries, got %d/%d' % (len(norm), len(shft)))

    table = [0] * 128
    for sc in range(1, MAIN_LAST + 1):
        for arr, flag in ((norm, 0x00), (shft, 0x80)):
            ch = arr[sc]
            if 0 < ch < 128 and table[ch] == 0:
                table[ch] = sc | flag

    # A serial terminal sends CR for Return and either 0x08 or 0x7F for
    # rubbing out. The table above already has CR (0x0d) and backspace
    # (0x08) because keyb_us.h spells them out; DEL does not appear in
    # the main block, so it is aliased onto backspace here. Newline is
    # aliased onto Return for terminals that send LF or CRLF.
    if table[0x7F] == 0:
        table[0x7F] = table[0x08]
    if table[0x0A] == 0:
        table[0x0A] = table[0x0D]

    named = {c: n for n, c in ((chr(i), i) for i in range(128))}
    lines = []
    for i in range(0, 128, 8):
        row = ', '.join('0x%02X' % v for v in table[i:i + 8])
        lines.append('    %s,' % row)

    mapped = sum(1 for v in table if v)
    with open(OUT, 'w') as f:
        f.write('/* generated by tools/mkkeymap.py from %s -- do not edit */\n' % SRC)
        f.write('/* ASCII -> Atari scancode; bit 7 set means the key needs shift. */\n')
        f.write('static const unsigned char uart_keymap[128] = {\n')
        f.write('\n'.join(lines))
        f.write('\n};\n')
    sys.stderr.write('%s: %d of 128 codes mapped\n' % (OUT, mapped))


main()
